version: "3"

volumes:
  dbdata:
  pgdata:

services:
  example:
    restart: always
    build: .
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./mongo_example:/example
      - ./postgres_example:/postgres_example
      - ./pattern_recipy:/pattern_recipy
    stdin_open: true # docker run -i
    tty: true # docker run -t
    command: bash

  mongodb:
    restart: always
    image: mongo:4.2.8
    env_file:
      - .env
    ports:
      - "47017:27017"
    expose:
      - "27017"
    volumes:
      - dbdata:/data/db
    
  postgres:
    restart: always
    image: postgres:alpine
    env_file:
      - .env
    environment:
      TZ: "Asia/Seoul"
      POSTGRES_PASSWORD: "password"
    ports:
      - "45432:5432"
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
