create table car (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	maker VARCHAR(100) NOT NULL,
	model VARCHAR(100) NOT NULL,
	price NUMERIC(19, 2) NOT NULL
);
insert into car (maker, model, price) values ('Mercedes-Benz', 'C-Class', 30075);
insert into car (maker, model, price) values ('Ford', 'Freestar', 44977);
insert into car (maker, model, price) values ('Maserati', 'Gran Sport', 16716);
insert into car (maker, model, price) values ('Nissan', 'Sentra', 54431);
insert into car (maker, model, price) values ('Buick', 'Skylark', 73202);
insert into car (maker, model, price) values ('Ford', 'F350', 36695);
insert into car (maker, model, price) values ('Infiniti', 'QX56', 62839);
insert into car (maker, model, price) values ('Kia', 'Spectra', 72645);
insert into car (maker, model, price) values ('Mercury', 'Mariner', 55055);
insert into car (maker, model, price) values ('Mercedes-Benz', 'SL-Class', 95968);
insert into car (maker, model, price) values ('Jaguar', 'XJ', 11762);
insert into car (maker, model, price) values ('Toyota', 'Previa', 76630);
insert into car (maker, model, price) values ('Buick', 'Electra', 86063);
insert into car (maker, model, price) values ('Saab', '9-5', 13142);
insert into car (maker, model, price) values ('Lexus', 'GS', 30666);
insert into car (maker, model, price) values ('Toyota', 'Celica', 45397);
insert into car (maker, model, price) values ('Mazda', '323', 78675);
insert into car (maker, model, price) values ('Mitsubishi', 'Sigma', 25946);
insert into car (maker, model, price) values ('Lincoln', 'Town Car', 94085);
insert into car (maker, model, price) values ('Mazda', 'B-Series', 10221);
insert into car (maker, model, price) values ('Mercury', 'Cougar', 90778);
insert into car (maker, model, price) values ('Ford', 'Escape', 77725);
insert into car (maker, model, price) values ('Mercury', 'Tracer', 65282);
insert into car (maker, model, price) values ('Lincoln', 'Town Car', 41185);
insert into car (maker, model, price) values ('Audi', 'A3', 98251);
insert into car (maker, model, price) values ('Ford', 'Freestar', 30021);
insert into car (maker, model, price) values ('Mercedes-Benz', 'Sprinter 2500', 79575);
insert into car (maker, model, price) values ('Mitsubishi', 'Truck', 79137);
insert into car (maker, model, price) values ('Mitsubishi', 'Galant', 29508);
insert into car (maker, model, price) values ('Oldsmobile', 'Alero', 41715);
insert into car (maker, model, price) values ('Ford', 'Aerostar', 60090);
insert into car (maker, model, price) values ('Plymouth', 'Voyager', 30908);
insert into car (maker, model, price) values ('BMW', '7 Series', 10337);
insert into car (maker, model, price) values ('Lincoln', 'MKT', 60460);
insert into car (maker, model, price) values ('Ford', 'Courier', 40693);
insert into car (maker, model, price) values ('Acura', 'TL', 35209);
insert into car (maker, model, price) values ('MINI', 'Countryman', 11050);
insert into car (maker, model, price) values ('Pontiac', 'Vibe', 90161);
insert into car (maker, model, price) values ('Subaru', 'Legacy', 89687);
insert into car (maker, model, price) values ('Mercedes-Benz', 'M-Class', 80230);
insert into car (maker, model, price) values ('Dodge', 'Durango', 24641);
insert into car (maker, model, price) values ('GMC', 'Safari', 49587);
insert into car (maker, model, price) values ('Chevrolet', '2500', 91618);
insert into car (maker, model, price) values ('Chevrolet', 'Sportvan G30', 31163);
insert into car (maker, model, price) values ('Ford', 'Escape', 37784);
insert into car (maker, model, price) values ('Dodge', 'Caliber', 82728);
insert into car (maker, model, price) values ('Subaru', 'Justy', 82939);
insert into car (maker, model, price) values ('Dodge', 'Stealth', 21562);
insert into car (maker, model, price) values ('Bentley', 'Arnage', 36034);
insert into car (maker, model, price) values ('Geo', 'Tracker', 71999);
insert into car (maker, model, price) values ('Pontiac', 'Grand Am', 43863);
insert into car (maker, model, price) values ('Jeep', 'Cherokee', 75968);
insert into car (maker, model, price) values ('Nissan', 'Altima', 82288);
insert into car (maker, model, price) values ('Mercedes-Benz', '300TE', 62972);
insert into car (maker, model, price) values ('Volkswagen', 'Touareg', 61173);
insert into car (maker, model, price) values ('Dodge', 'Caravan', 93007);
insert into car (maker, model, price) values ('Volvo', 'S80', 83022);
insert into car (maker, model, price) values ('Chrysler', '300C', 11439);
insert into car (maker, model, price) values ('Chevrolet', 'Cavalier', 29889);
insert into car (maker, model, price) values ('Ford', 'Taurus', 54384);
insert into car (maker, model, price) values ('Mercury', 'Cougar', 75825);
insert into car (maker, model, price) values ('Suzuki', 'Grand Vitara', 72397);
insert into car (maker, model, price) values ('Chevrolet', 'Sportvan G20', 59380);
insert into car (maker, model, price) values ('Pontiac', '1000', 75211);
insert into car (maker, model, price) values ('Chevrolet', 'Corvette', 58674);
insert into car (maker, model, price) values ('Honda', 'Accord', 98154);
insert into car (maker, model, price) values ('Ford', 'F350', 81998);
insert into car (maker, model, price) values ('Ford', 'GT500', 44547);
insert into car (maker, model, price) values ('Acura', 'TSX', 87366);
insert into car (maker, model, price) values ('Mazda', 'B2000', 49446);
insert into car (maker, model, price) values ('Infiniti', 'QX', 39868);
insert into car (maker, model, price) values ('Ford', 'F350', 36255);
insert into car (maker, model, price) values ('Lincoln', 'Town Car', 65172);
insert into car (maker, model, price) values ('Mazda', 'MX-5', 67638);
insert into car (maker, model, price) values ('Chevrolet', 'Suburban 1500', 43095);
insert into car (maker, model, price) values ('Ford', 'Mustang', 82109);
insert into car (maker, model, price) values ('Ford', 'Bronco II', 83899);
insert into car (maker, model, price) values ('Toyota', '4Runner', 92291);
insert into car (maker, model, price) values ('Lexus', 'IS', 60090);
insert into car (maker, model, price) values ('Mercedes-Benz', '300SL', 34989);
insert into car (maker, model, price) values ('Hyundai', 'Elantra', 18631);
insert into car (maker, model, price) values ('Chevrolet', 'G-Series 2500', 92466);
insert into car (maker, model, price) values ('Honda', 'Civic', 84633);
insert into car (maker, model, price) values ('Buick', 'Riviera', 23760);
insert into car (maker, model, price) values ('Volvo', 'C70', 60445);
insert into car (maker, model, price) values ('BMW', '600', 59812);
insert into car (maker, model, price) values ('Chrysler', 'Sebring', 40139);
insert into car (maker, model, price) values ('Daewoo', 'Nubira', 77799);
insert into car (maker, model, price) values ('Ford', 'Focus', 47597);
insert into car (maker, model, price) values ('Nissan', '240SX', 53299);
insert into car (maker, model, price) values ('Jeep', 'Cherokee', 55795);
insert into car (maker, model, price) values ('Infiniti', 'Q', 36485);
insert into car (maker, model, price) values ('GMC', 'Sierra 1500', 29059);
insert into car (maker, model, price) values ('Pontiac', 'Torrent', 56461);
insert into car (maker, model, price) values ('Isuzu', 'Oasis', 14204);
insert into car (maker, model, price) values ('Ford', 'Explorer Sport Trac', 64062);
insert into car (maker, model, price) values ('Land Rover', 'Discovery', 37547);
insert into car (maker, model, price) values ('Toyota', 'Tacoma Xtra', 51512);
insert into car (maker, model, price) values ('Lotus', 'Elise', 20177);
insert into car (maker, model, price) values ('Dodge', 'Ram 1500', 92578);
insert into car (maker, model, price) values ('Honda', 'Civic', 98490);
insert into car (maker, model, price) values ('Volkswagen', 'Jetta', 53263);
insert into car (maker, model, price) values ('Subaru', 'Outback', 79698);
insert into car (maker, model, price) values ('BMW', 'M5', 16590);
insert into car (maker, model, price) values ('Buick', 'Park Avenue', 18154);
insert into car (maker, model, price) values ('Mercury', 'Sable', 10324);
insert into car (maker, model, price) values ('Chevrolet', 'Corvette', 40829);
insert into car (maker, model, price) values ('Pontiac', 'Grand Prix', 47449);
insert into car (maker, model, price) values ('Subaru', 'Baja', 32882);
insert into car (maker, model, price) values ('Volkswagen', 'Fox', 53564);
insert into car (maker, model, price) values ('Mazda', 'Miata MX-5', 64299);
insert into car (maker, model, price) values ('Mitsubishi', 'Outlander', 49156);
insert into car (maker, model, price) values ('GMC', 'Envoy', 63159);
insert into car (maker, model, price) values ('Saab', '9-5', 38859);
insert into car (maker, model, price) values ('Jaguar', 'XF', 26764);
insert into car (maker, model, price) values ('Mazda', '323', 45393);
insert into car (maker, model, price) values ('Honda', 'Pilot', 97880);
insert into car (maker, model, price) values ('Lincoln', 'LS', 47441);
insert into car (maker, model, price) values ('Ford', 'Econoline E350', 61595);
insert into car (maker, model, price) values ('GMC', 'Yukon XL 1500', 37058);
insert into car (maker, model, price) values ('Toyota', '4Runner', 77286);
insert into car (maker, model, price) values ('Lexus', 'ES', 38381);
insert into car (maker, model, price) values ('Kia', 'Amanti', 95949);
insert into car (maker, model, price) values ('Ford', 'Ranger', 78393);
insert into car (maker, model, price) values ('Dodge', 'Ramcharger', 99101);
insert into car (maker, model, price) values ('Plymouth', 'Laser', 55236);
insert into car (maker, model, price) values ('Chevrolet', 'HHR', 59883);
insert into car (maker, model, price) values ('Toyota', 'Sienna', 92965);
insert into car (maker, model, price) values ('Mitsubishi', 'Galant', 46684);
insert into car (maker, model, price) values ('Nissan', 'Sentra', 42829);
insert into car (maker, model, price) values ('Chevrolet', 'Express 3500', 60220);
insert into car (maker, model, price) values ('Audi', 'A8', 14679);
insert into car (maker, model, price) values ('Mercedes-Benz', 'SL65 AMG', 40675);
insert into car (maker, model, price) values ('Scion', 'FR-S', 68940);
insert into car (maker, model, price) values ('Cadillac', 'Escalade EXT', 72662);
insert into car (maker, model, price) values ('Mazda', 'B-Series', 81562);
insert into car (maker, model, price) values ('Toyota', 'Previa', 69624);
insert into car (maker, model, price) values ('Toyota', 'Tacoma', 93884);
insert into car (maker, model, price) values ('Acura', 'RL', 31951);
insert into car (maker, model, price) values ('Acura', 'NSX', 39780);
insert into car (maker, model, price) values ('Jeep', 'Grand Cherokee', 18236);
insert into car (maker, model, price) values ('Ford', 'E-350 Super Duty', 61215);
insert into car (maker, model, price) values ('Mitsubishi', 'RVR', 85863);
insert into car (maker, model, price) values ('Audi', 'S8', 74143);
insert into car (maker, model, price) values ('Cadillac', 'Seville', 12621);
insert into car (maker, model, price) values ('Ford', 'Laser', 26441);
insert into car (maker, model, price) values ('Acura', 'MDX', 21802);
insert into car (maker, model, price) values ('Audi', 'Q5', 47806);
insert into car (maker, model, price) values ('Toyota', 'Celica', 27430);
insert into car (maker, model, price) values ('Suzuki', 'Kizashi', 53975);
insert into car (maker, model, price) values ('Mercedes-Benz', 'C-Class', 35252);
insert into car (maker, model, price) values ('Ford', 'E-Series', 90902);
insert into car (maker, model, price) values ('Mitsubishi', 'Lancer', 10181);
insert into car (maker, model, price) values ('Pontiac', 'Parisienne', 35830);
insert into car (maker, model, price) values ('Hyundai', 'Accent', 61747);
insert into car (maker, model, price) values ('Porsche', '911', 53670);
insert into car (maker, model, price) values ('Mitsubishi', 'Eclipse', 16558);
insert into car (maker, model, price) values ('Suzuki', 'Forenza', 60415);
insert into car (maker, model, price) values ('Pontiac', 'Bonneville', 89618);
insert into car (maker, model, price) values ('Ford', 'Taurus', 14496);
insert into car (maker, model, price) values ('Chevrolet', 'Beretta', 96435);
insert into car (maker, model, price) values ('Chevrolet', 'Silverado 3500', 34548);
insert into car (maker, model, price) values ('Ford', 'Tempo', 91403);
insert into car (maker, model, price) values ('Chevrolet', 'Tahoe', 99751);
insert into car (maker, model, price) values ('Nissan', 'Maxima', 61804);
insert into car (maker, model, price) values ('Ford', 'Taurus X', 34637);
insert into car (maker, model, price) values ('Audi', '5000CS', 93706);
insert into car (maker, model, price) values ('Plymouth', 'Acclaim', 11233);
insert into car (maker, model, price) values ('Lamborghini', 'Diablo', 76509);
insert into car (maker, model, price) values ('Chevrolet', 'Astro', 49688);
insert into car (maker, model, price) values ('Chevrolet', 'Blazer', 23696);
insert into car (maker, model, price) values ('Honda', 'Ridgeline', 63930);
insert into car (maker, model, price) values ('Pontiac', 'Grand Prix', 41248);
insert into car (maker, model, price) values ('GMC', 'Yukon', 60618);
insert into car (maker, model, price) values ('Chevrolet', 'Corvette', 92757);
insert into car (maker, model, price) values ('Mazda', 'MX-5', 40699);
insert into car (maker, model, price) values ('Toyota', 'Celica', 81671);
insert into car (maker, model, price) values ('Subaru', 'Baja', 14091);
insert into car (maker, model, price) values ('Kia', 'Sportage', 25900);
insert into car (maker, model, price) values ('Lincoln', 'Navigator', 24307);
insert into car (maker, model, price) values ('Suzuki', 'Swift', 37531);
insert into car (maker, model, price) values ('Toyota', 'Venza', 86310);
insert into car (maker, model, price) values ('Isuzu', 'Rodeo Sport', 36530);
insert into car (maker, model, price) values ('Jeep', 'Commander', 27030);
insert into car (maker, model, price) values ('Chevrolet', 'SSR', 41308);
insert into car (maker, model, price) values ('Chevrolet', 'Sportvan G20', 82825);
insert into car (maker, model, price) values ('Plymouth', 'Sundance', 64040);
insert into car (maker, model, price) values ('Toyota', 'Tundra', 67386);
insert into car (maker, model, price) values ('Mazda', 'Miata MX-5', 41941);
insert into car (maker, model, price) values ('Suzuki', 'SX4', 12037);
insert into car (maker, model, price) values ('Nissan', 'Titan', 36302);
insert into car (maker, model, price) values ('Volkswagen', 'GTI', 14432);
insert into car (maker, model, price) values ('Ford', 'Bronco', 38736);
insert into car (maker, model, price) values ('Pontiac', 'Grand Am', 23106);
insert into car (maker, model, price) values ('MINI', 'Countryman', 48528);
insert into car (maker, model, price) values ('GMC', 'Savana', 74402);
insert into car (maker, model, price) values ('Chrysler', 'New Yorker', 86190);
insert into car (maker, model, price) values ('Buick', 'LeSabre', 31052);
insert into car (maker, model, price) values ('Alfa Romeo', 'Spider', 54158);
insert into car (maker, model, price) values ('GMC', 'Sierra', 80872);
insert into car (maker, model, price) values ('Oldsmobile', 'Silhouette', 94105);
insert into car (maker, model, price) values ('Lexus', 'LS Hybrid', 82740);
insert into car (maker, model, price) values ('Buick', 'LeSabre', 70047);
insert into car (maker, model, price) values ('Volkswagen', 'Corrado', 69251);
insert into car (maker, model, price) values ('Pontiac', 'Daewoo Kalos', 76980);
insert into car (maker, model, price) values ('Volkswagen', 'Passat', 45379);
insert into car (maker, model, price) values ('Suzuki', 'Grand Vitara', 71997);
insert into car (maker, model, price) values ('Ford', 'Club Wagon', 74103);
insert into car (maker, model, price) values ('Subaru', 'Justy', 26062);
insert into car (maker, model, price) values ('Jeep', 'Grand Cherokee', 18069);
insert into car (maker, model, price) values ('Volkswagen', 'GTI', 14801);
insert into car (maker, model, price) values ('Maybach', '62', 45355);
insert into car (maker, model, price) values ('Infiniti', 'G', 42225);
insert into car (maker, model, price) values ('BMW', '7 Series', 92090);
insert into car (maker, model, price) values ('Porsche', 'Cayenne', 37886);
insert into car (maker, model, price) values ('Toyota', 'Tundra', 22629);
insert into car (maker, model, price) values ('Toyota', 'TundraMax', 18842);
insert into car (maker, model, price) values ('Toyota', 'Tundra', 13585);
insert into car (maker, model, price) values ('Honda', 'S2000', 44574);
insert into car (maker, model, price) values ('GMC', 'Savana 2500', 48925);
insert into car (maker, model, price) values ('GMC', 'Yukon XL 2500', 69881);
insert into car (maker, model, price) values ('Chevrolet', 'Corvette', 95436);
insert into car (maker, model, price) values ('Pontiac', 'Bonneville', 26452);
insert into car (maker, model, price) values ('Chevrolet', 'Aveo', 77166);
insert into car (maker, model, price) values ('Plymouth', 'Colt Vista', 56740);
insert into car (maker, model, price) values ('Mitsubishi', 'Truck', 59846);
insert into car (maker, model, price) values ('Ford', 'Expedition EL', 53958);
insert into car (maker, model, price) values ('Mercury', 'Sable', 70076);
insert into car (maker, model, price) values ('Lincoln', 'MKX', 13890);
insert into car (maker, model, price) values ('Chrysler', 'Town & Country', 23772);
insert into car (maker, model, price) values ('Ford', 'Econoline E150', 59171);
insert into car (maker, model, price) values ('Mitsubishi', 'Montero', 64514);
insert into car (maker, model, price) values ('Chevrolet', 'Blazer', 32520);
insert into car (maker, model, price) values ('Chrysler', 'LHS', 31664);
insert into car (maker, model, price) values ('Mercury', 'Sable', 25578);
insert into car (maker, model, price) values ('Mercury', 'Sable', 34835);
insert into car (maker, model, price) values ('Ford', 'Mustang', 62502);
insert into car (maker, model, price) values ('Mercedes-Benz', 'M-Class', 65628);
insert into car (maker, model, price) values ('Mercedes-Benz', '300CE', 45423);
insert into car (maker, model, price) values ('Lotus', 'Esprit', 44742);
insert into car (maker, model, price) values ('Mitsubishi', 'Montero Sport', 71824);
insert into car (maker, model, price) values ('Chrysler', 'Crossfire', 18882);
insert into car (maker, model, price) values ('Chevrolet', 'Silverado 1500', 23580);
insert into car (maker, model, price) values ('Jaguar', 'S-Type', 18804);
insert into car (maker, model, price) values ('Ford', 'Thunderbird', 99826);
insert into car (maker, model, price) values ('Volkswagen', 'Scirocco', 18116);
insert into car (maker, model, price) values ('Volkswagen', 'R32', 93202);
insert into car (maker, model, price) values ('Mitsubishi', 'Galant', 72341);
insert into car (maker, model, price) values ('Suzuki', 'Forenza', 51658);
insert into car (maker, model, price) values ('Hyundai', 'Accent', 59803);
insert into car (maker, model, price) values ('Chevrolet', 'Suburban 1500', 69729);
insert into car (maker, model, price) values ('GMC', 'Savana 2500', 75048);
insert into car (maker, model, price) values ('Toyota', 'Corolla', 16582);
insert into car (maker, model, price) values ('Ferrari', 'California', 14385);
insert into car (maker, model, price) values ('BMW', '525', 83804);
insert into car (maker, model, price) values ('Audi', 'riolet', 34181);
insert into car (maker, model, price) values ('Lexus', 'LS', 98685);
insert into car (maker, model, price) values ('Mercedes-Benz', 'W201', 97423);
insert into car (maker, model, price) values ('Honda', 'Insight', 94911);
insert into car (maker, model, price) values ('Chevrolet', 'Corvette', 61202);
insert into car (maker, model, price) values ('Mercury', 'Capri', 66604);
insert into car (maker, model, price) values ('Chevrolet', 'Corsica', 60637);
insert into car (maker, model, price) values ('Cadillac', 'Escalade EXT', 76969);
insert into car (maker, model, price) values ('Pontiac', 'Grand Am', 49500);
insert into car (maker, model, price) values ('Chevrolet', 'Express 1500', 69134);
insert into car (maker, model, price) values ('Maybach', '57', 65374);
insert into car (maker, model, price) values ('Mercedes-Benz', 'SLK-Class', 16883);
insert into car (maker, model, price) values ('Ford', 'Mustang', 59525);
insert into car (maker, model, price) values ('Ford', 'Ranger', 22543);
insert into car (maker, model, price) values ('Ford', 'Bronco', 14853);
insert into car (maker, model, price) values ('Chevrolet', 'Prizm', 35414);
insert into car (maker, model, price) values ('Jeep', 'Wrangler', 32837);
insert into car (maker, model, price) values ('Mitsubishi', 'Diamante', 50928);
insert into car (maker, model, price) values ('Mercury', 'Tracer', 62897);
insert into car (maker, model, price) values ('Volkswagen', 'Golf', 17937);
insert into car (maker, model, price) values ('Lexus', 'RX Hybrid', 60969);
insert into car (maker, model, price) values ('Ford', 'E250', 70972);
insert into car (maker, model, price) values ('Ford', 'Tempo', 84743);
insert into car (maker, model, price) values ('Pontiac', 'Fiero', 33417);
insert into car (maker, model, price) values ('Lexus', 'GX', 82489);
insert into car (maker, model, price) values ('Mercury', 'Cougar', 47334);
insert into car (maker, model, price) values ('Kia', 'Spectra', 17575);
insert into car (maker, model, price) values ('Kia', 'Sportage', 38613);
insert into car (maker, model, price) values ('Volkswagen', 'New Beetle', 37479);
insert into car (maker, model, price) values ('Honda', 'CR-X', 37276);
insert into car (maker, model, price) values ('Toyota', 'Celica', 63323);
insert into car (maker, model, price) values ('Rolls-Royce', 'Ghost', 70192);
insert into car (maker, model, price) values ('Lexus', 'LX', 33166);
insert into car (maker, model, price) values ('Mercedes-Benz', 'R-Class', 83097);
insert into car (maker, model, price) values ('Nissan', 'Pathfinder', 83863);
insert into car (maker, model, price) values ('GMC', 'Savana 2500', 66625);
insert into car (maker, model, price) values ('Ford', 'Excursion', 88626);
insert into car (maker, model, price) values ('Lotus', 'Evora', 81815);
insert into car (maker, model, price) values ('BMW', '330', 46905);
insert into car (maker, model, price) values ('Toyota', 'Tacoma', 68619);
insert into car (maker, model, price) values ('Ford', 'Ranger', 41685);
insert into car (maker, model, price) values ('Pontiac', 'Sunbird', 88817);
insert into car (maker, model, price) values ('Saturn', 'S-Series', 80808);
insert into car (maker, model, price) values ('Dodge', 'Dakota', 39463);
insert into car (maker, model, price) values ('Porsche', '911', 16414);
insert into car (maker, model, price) values ('Mercedes-Benz', 'E-Class', 53581);
insert into car (maker, model, price) values ('Hummer', 'H3T', 21478);
insert into car (maker, model, price) values ('Volvo', 'S60', 80293);
insert into car (maker, model, price) values ('Toyota', 'Solara', 86062);
insert into car (maker, model, price) values ('Geo', 'Prizm', 16058);
insert into car (maker, model, price) values ('Volkswagen', 'Jetta', 99963);
insert into car (maker, model, price) values ('Ford', 'Taurus', 82675);
insert into car (maker, model, price) values ('Chrysler', 'Crossfire', 29770);
insert into car (maker, model, price) values ('Dodge', 'Spirit', 18893);
insert into car (maker, model, price) values ('Honda', 'S2000', 51865);
insert into car (maker, model, price) values ('Aston Martin', 'Vanquish S', 80252);
insert into car (maker, model, price) values ('Mercury', 'Mountaineer', 90463);
insert into car (maker, model, price) values ('Nissan', 'Titan', 46738);
insert into car (maker, model, price) values ('Acura', 'ZDX', 74057);
insert into car (maker, model, price) values ('Buick', 'Park Avenue', 56488);
insert into car (maker, model, price) values ('Audi', '90', 12623);
insert into car (maker, model, price) values ('BMW', '600', 86678);
insert into car (maker, model, price) values ('Lamborghini', 'Countach', 55276);
insert into car (maker, model, price) values ('Maybach', '57', 17907);
insert into car (maker, model, price) values ('Cadillac', 'Escalade', 69210);
insert into car (maker, model, price) values ('Toyota', 'TundraMax', 55998);
insert into car (maker, model, price) values ('Mitsubishi', 'Pajero', 60698);
insert into car (maker, model, price) values ('Dodge', 'D250', 26257);
insert into car (maker, model, price) values ('Pontiac', 'LeMans', 17099);
insert into car (maker, model, price) values ('Acura', 'ZDX', 55025);
insert into car (maker, model, price) values ('Mitsubishi', 'Mirage', 78514);
insert into car (maker, model, price) values ('Infiniti', 'QX56', 92893);
insert into car (maker, model, price) values ('Toyota', 'Camry', 62977);
insert into car (maker, model, price) values ('Buick', 'Electra', 92056);
insert into car (maker, model, price) values ('Chevrolet', 'Express 3500', 11756);
insert into car (maker, model, price) values ('Hyundai', 'Veracruz', 90143);
insert into car (maker, model, price) values ('Lexus', 'SC', 17347);
insert into car (maker, model, price) values ('Maserati', 'Quattroporte', 25284);
insert into car (maker, model, price) values ('Acura', 'TL', 30770);
insert into car (maker, model, price) values ('Chevrolet', 'Astro', 61493);
insert into car (maker, model, price) values ('Saab', '9-5', 47142);
insert into car (maker, model, price) values ('Mitsubishi', 'Lancer', 18927);
insert into car (maker, model, price) values ('Nissan', 'Sentra', 45138);
insert into car (maker, model, price) values ('Chevrolet', 'Corvette', 50180);
insert into car (maker, model, price) values ('Mitsubishi', 'Chariot', 90835);
insert into car (maker, model, price) values ('Chevrolet', 'Silverado 3500', 21207);
insert into car (maker, model, price) values ('Ford', 'Transit Connect', 25263);
insert into car (maker, model, price) values ('Mercedes-Benz', 'SLK-Class', 48041);
insert into car (maker, model, price) values ('Ford', 'Econoline E150', 10112);
insert into car (maker, model, price) values ('Audi', '100', 71485);
insert into car (maker, model, price) values ('Mercedes-Benz', 'SLK-Class', 70422);
insert into car (maker, model, price) values ('Honda', 'Civic', 37011);
insert into car (maker, model, price) values ('Oldsmobile', 'Silhouette', 46175);
insert into car (maker, model, price) values ('Maserati', 'Quattroporte', 33100);
insert into car (maker, model, price) values ('Ford', 'Thunderbird', 79125);
insert into car (maker, model, price) values ('Pontiac', 'Sunfire', 67807);
insert into car (maker, model, price) values ('Chevrolet', 'Silverado 2500', 43244);
insert into car (maker, model, price) values ('Oldsmobile', 'Ciera', 16930);
insert into car (maker, model, price) values ('Mazda', 'Protege', 23892);
insert into car (maker, model, price) values ('Fiat', '500', 57560);
insert into car (maker, model, price) values ('Mitsubishi', 'Eclipse', 67032);
insert into car (maker, model, price) values ('Toyota', 'Matrix', 83675);
insert into car (maker, model, price) values ('Toyota', '4Runner', 32962);
insert into car (maker, model, price) values ('Audi', '100', 59334);
insert into car (maker, model, price) values ('Hyundai', 'Sonata', 60106);
insert into car (maker, model, price) values ('Lexus', 'HS', 22430);
insert into car (maker, model, price) values ('Plymouth', 'Colt', 41696);
insert into car (maker, model, price) values ('Pontiac', 'Grand Am', 28030);
insert into car (maker, model, price) values ('Dodge', 'Ram 1500', 21860);
insert into car (maker, model, price) values ('Mercedes-Benz', 'S-Class', 62396);
insert into car (maker, model, price) values ('Chrysler', 'Town & Country', 99794);
insert into car (maker, model, price) values ('Honda', 'Odyssey', 86606);
insert into car (maker, model, price) values ('Volvo', 'S40', 14531);
insert into car (maker, model, price) values ('Chevrolet', 'Silverado 2500', 92815);
insert into car (maker, model, price) values ('Volvo', 'S40', 98977);
insert into car (maker, model, price) values ('Pontiac', 'Firebird', 22319);
insert into car (maker, model, price) values ('Hyundai', 'Santa Fe', 40576);
insert into car (maker, model, price) values ('GMC', 'Sonoma Club', 11132);
insert into car (maker, model, price) values ('Mitsubishi', 'Outlander', 18797);
insert into car (maker, model, price) values ('Pontiac', 'Monterey', 25724);
insert into car (maker, model, price) values ('Nissan', 'Frontier', 77140);
insert into car (maker, model, price) values ('Dodge', 'Dakota Club', 32921);
insert into car (maker, model, price) values ('Subaru', 'SVX', 78383);
insert into car (maker, model, price) values ('Pontiac', 'Grand Am', 64315);
insert into car (maker, model, price) values ('Mercury', 'Grand Marquis', 76531);
insert into car (maker, model, price) values ('Ford', 'F350', 63689);
insert into car (maker, model, price) values ('Ford', 'Escape', 75879);
insert into car (maker, model, price) values ('Nissan', 'Murano', 78994);
insert into car (maker, model, price) values ('Dodge', 'Ram Wagon B350', 22740);
insert into car (maker, model, price) values ('Ford', 'Freestyle', 56473);
insert into car (maker, model, price) values ('Lincoln', 'Continental Mark VII', 36392);
insert into car (maker, model, price) values ('Mitsubishi', 'Diamante', 33316);
insert into car (maker, model, price) values ('Ford', 'Aerostar', 91286);
insert into car (maker, model, price) values ('Ford', 'Expedition', 28782);
insert into car (maker, model, price) values ('Chevrolet', 'Silverado', 93660);
insert into car (maker, model, price) values ('Buick', 'Coachbuilder', 60633);
insert into car (maker, model, price) values ('Jaguar', 'XK Series', 87393);
insert into car (maker, model, price) values ('Porsche', '911', 70977);
insert into car (maker, model, price) values ('Dodge', 'Intrepid', 57698);
insert into car (maker, model, price) values ('Suzuki', 'Esteem', 25247);
insert into car (maker, model, price) values ('Ford', 'Mustang', 39622);
insert into car (maker, model, price) values ('Volkswagen', 'Cabriolet', 81478);
insert into car (maker, model, price) values ('Chevrolet', '2500', 74384);
insert into car (maker, model, price) values ('Bentley', 'Continental Flying Spur', 68969);
insert into car (maker, model, price) values ('Pontiac', 'Bonneville', 85576);
insert into car (maker, model, price) values ('Cadillac', 'STS', 31666);
insert into car (maker, model, price) values ('Saab', '9000', 95173);
insert into car (maker, model, price) values ('Toyota', 'Venza', 18676);
insert into car (maker, model, price) values ('Nissan', 'Pathfinder Armada', 92145);
insert into car (maker, model, price) values ('Mercedes-Benz', 'GLK-Class', 60080);
insert into car (maker, model, price) values ('Mercury', 'Lynx', 33366);
insert into car (maker, model, price) values ('Mazda', 'B-Series', 37652);
insert into car (maker, model, price) values ('Oldsmobile', 'Aurora', 23855);
insert into car (maker, model, price) values ('Chevrolet', 'Express', 45122);
insert into car (maker, model, price) values ('Toyota', 'Sequoia', 95032);
insert into car (maker, model, price) values ('Subaru', 'SVX', 55774);
insert into car (maker, model, price) values ('Geo', 'Prizm', 24758);
insert into car (maker, model, price) values ('Jeep', 'Grand Cherokee', 81384);
insert into car (maker, model, price) values ('Chevrolet', '2500', 95230);
insert into car (maker, model, price) values ('Suzuki', 'XL7', 96569);
insert into car (maker, model, price) values ('GMC', 'Yukon XL 1500', 36503);
insert into car (maker, model, price) values ('Acura', 'SLX', 55970);
insert into car (maker, model, price) values ('GMC', 'Sierra', 34988);
insert into car (maker, model, price) values ('Pontiac', 'Fiero', 17968);
insert into car (maker, model, price) values ('Audi', 'Coupe GT', 24435);
insert into car (maker, model, price) values ('Cadillac', 'Escalade ESV', 42648);
insert into car (maker, model, price) values ('Chevrolet', 'Camaro', 10889);
insert into car (maker, model, price) values ('Toyota', 'RAV4', 35570);
insert into car (maker, model, price) values ('Mercedes-Benz', 'CL-Class', 77681);
insert into car (maker, model, price) values ('Mitsubishi', 'Lancer Evolution', 19230);
insert into car (maker, model, price) values ('Chevrolet', 'Corvette', 20539);
insert into car (maker, model, price) values ('Jensen', 'Interceptor', 42224);
insert into car (maker, model, price) values ('Ford', 'Th!nk', 58402);
insert into car (maker, model, price) values ('Mitsubishi', 'Mighty Max', 95931);
insert into car (maker, model, price) values ('GMC', 'Savana', 53115);
insert into car (maker, model, price) values ('Pontiac', 'Grand Am', 38535);
insert into car (maker, model, price) values ('GMC', 'Rally Wagon 3500', 63309);
insert into car (maker, model, price) values ('Pontiac', 'Bonneville', 26474);
insert into car (maker, model, price) values ('Mercedes-Benz', 'E-Class', 44082);
insert into car (maker, model, price) values ('Kia', 'Sportage', 71137);
insert into car (maker, model, price) values ('Suzuki', 'SJ', 41972);
insert into car (maker, model, price) values ('Toyota', '4Runner', 53523);
insert into car (maker, model, price) values ('Buick', 'Skyhawk', 40142);
insert into car (maker, model, price) values ('Dodge', 'Ram Van 1500', 99065);
insert into car (maker, model, price) values ('Jaguar', 'XK Series', 68411);
insert into car (maker, model, price) values ('Chevrolet', 'Tracker', 70964);
insert into car (maker, model, price) values ('Chevrolet', 'Silverado 2500', 84732);
insert into car (maker, model, price) values ('Audi', 'Q7', 87716);
insert into car (maker, model, price) values ('Subaru', 'SVX', 43964);
insert into car (maker, model, price) values ('Buick', 'Somerset', 27550);
insert into car (maker, model, price) values ('Volkswagen', 'Jetta', 44055);
insert into car (maker, model, price) values ('BMW', '5 Series', 59244);
insert into car (maker, model, price) values ('Toyota', 'Xtra', 39590);
insert into car (maker, model, price) values ('Suzuki', 'Daewoo Magnus', 19761);
insert into car (maker, model, price) values ('Dodge', 'Caliber', 41802);
insert into car (maker, model, price) values ('Hyundai', 'Tiburon', 96908);
insert into car (maker, model, price) values ('Lexus', 'LX', 76489);
insert into car (maker, model, price) values ('Maserati', 'Quattroporte', 29108);
insert into car (maker, model, price) values ('Volvo', 'S80', 58236);
insert into car (maker, model, price) values ('Ferrari', 'F430 Spider', 82833);
insert into car (maker, model, price) values ('Mazda', 'RX-7', 72166);
insert into car (maker, model, price) values ('Pontiac', 'GTO', 90712);
insert into car (maker, model, price) values ('Mercedes-Benz', 'CL-Class', 83276);
insert into car (maker, model, price) values ('Mercury', 'Mystique', 59835);
insert into car (maker, model, price) values ('Mitsubishi', 'Starion', 79337);
insert into car (maker, model, price) values ('Chevrolet', 'Cavalier', 26436);
insert into car (maker, model, price) values ('Toyota', 'Celica', 83508);
insert into car (maker, model, price) values ('Chevrolet', 'Monte Carlo', 95430);
insert into car (maker, model, price) values ('Lexus', 'SC', 32515);
insert into car (maker, model, price) values ('Mercedes-Benz', 'E-Class', 51215);
insert into car (maker, model, price) values ('Chevrolet', 'Silverado 2500', 39078);
insert into car (maker, model, price) values ('Nissan', 'Titan', 91958);
insert into car (maker, model, price) values ('Ford', 'Escape', 43190);
insert into car (maker, model, price) values ('Isuzu', 'Impulse', 87534);
insert into car (maker, model, price) values ('Chrysler', 'Fifth Ave', 51055);
insert into car (maker, model, price) values ('Kia', 'Spectra', 61182);
insert into car (maker, model, price) values ('Cadillac', 'Eldorado', 86722);
insert into car (maker, model, price) values ('Plymouth', 'Voyager', 40454);
insert into car (maker, model, price) values ('Kia', 'Amanti', 88530);
insert into car (maker, model, price) values ('Chevrolet', 'Cavalier', 14392);
insert into car (maker, model, price) values ('GMC', '2500', 41950);
insert into car (maker, model, price) values ('Jeep', 'Grand Cherokee', 38151);
insert into car (maker, model, price) values ('Toyota', 'Land Cruiser', 36969);
insert into car (maker, model, price) values ('Pontiac', 'Firefly', 60245);
insert into car (maker, model, price) values ('Plymouth', 'Breeze', 14524);
insert into car (maker, model, price) values ('Hummer', 'H1', 72277);
insert into car (maker, model, price) values ('Pontiac', 'LeMans', 88321);
insert into car (maker, model, price) values ('Buick', 'Century', 99286);
insert into car (maker, model, price) values ('Buick', 'Regal', 63407);
insert into car (maker, model, price) values ('Pontiac', 'Grand Prix', 50679);
insert into car (maker, model, price) values ('Lexus', 'ES', 86072);
insert into car (maker, model, price) values ('Suzuki', 'Forenza', 87813);
insert into car (maker, model, price) values ('Honda', 'Civic', 17960);
insert into car (maker, model, price) values ('Lotus', 'Esprit', 71840);
insert into car (maker, model, price) values ('Volkswagen', 'Eurovan', 30985);
insert into car (maker, model, price) values ('Ford', 'Laser', 16286);
insert into car (maker, model, price) values ('Acura', 'Legend', 90770);
insert into car (maker, model, price) values ('Toyota', 'Venza', 19460);
insert into car (maker, model, price) values ('BMW', 'M', 17795);
insert into car (maker, model, price) values ('Chrysler', '300', 13383);
insert into car (maker, model, price) values ('Ford', 'Crown Victoria', 94894);
insert into car (maker, model, price) values ('Ford', 'Th!nk', 85967);
insert into car (maker, model, price) values ('Nissan', 'Altima', 24473);
insert into car (maker, model, price) values ('Nissan', 'Sentra', 55825);
insert into car (maker, model, price) values ('Mercedes-Benz', '190E', 41966);
insert into car (maker, model, price) values ('Aston Martin', 'V8 Vantage', 30335);
insert into car (maker, model, price) values ('Infiniti', 'M', 61489);
insert into car (maker, model, price) values ('Nissan', 'Quest', 55549);
insert into car (maker, model, price) values ('Toyota', 'Prius', 77645);
insert into car (maker, model, price) values ('Oldsmobile', '88', 30130);
insert into car (maker, model, price) values ('Lamborghini', 'Diablo', 14025);
insert into car (maker, model, price) values ('BMW', '6 Series', 50861);
insert into car (maker, model, price) values ('Porsche', '911', 15808);
insert into car (maker, model, price) values ('Pontiac', 'Sunbird', 73838);
insert into car (maker, model, price) values ('GMC', 'Safari', 44520);
insert into car (maker, model, price) values ('Toyota', 'Tercel', 30353);
insert into car (maker, model, price) values ('Lexus', 'LS', 39376);
insert into car (maker, model, price) values ('Mercury', 'Marauder', 49665);
insert into car (maker, model, price) values ('Ford', 'Freestyle', 91122);
insert into car (maker, model, price) values ('Dodge', 'Neon', 19023);
insert into car (maker, model, price) values ('Mercedes-Benz', 'E-Class', 22025);
insert into car (maker, model, price) values ('Ford', 'Mustang', 77468);
insert into car (maker, model, price) values ('Volvo', 'XC90', 98758);
insert into car (maker, model, price) values ('GMC', 'Envoy', 80163);
insert into car (maker, model, price) values ('Volvo', 'V50', 72140);
insert into car (maker, model, price) values ('GMC', 'Savana 1500', 73504);
insert into car (maker, model, price) values ('Toyota', 'Avalon', 57599);
insert into car (maker, model, price) values ('BMW', '600', 45145);
insert into car (maker, model, price) values ('Suzuki', 'XL-7', 71268);
insert into car (maker, model, price) values ('Mitsubishi', 'Endeavor', 36831);
insert into car (maker, model, price) values ('Hyundai', 'XG350', 15311);
insert into car (maker, model, price) values ('Mitsubishi', 'Pajero', 58982);
insert into car (maker, model, price) values ('Ford', 'E150', 40437);
insert into car (maker, model, price) values ('GMC', 'Yukon XL 2500', 20540);
insert into car (maker, model, price) values ('Kia', 'Sephia', 27840);
insert into car (maker, model, price) values ('Chevrolet', 'Corvette', 78005);
insert into car (maker, model, price) values ('Mercedes-Benz', 'CL-Class', 20330);
insert into car (maker, model, price) values ('Ford', 'Fusion', 67102);
insert into car (maker, model, price) values ('Mercedes-Benz', 'G55 AMG', 18326);
insert into car (maker, model, price) values ('Mitsubishi', 'Lancer', 26453);
insert into car (maker, model, price) values ('Volkswagen', 'New Beetle', 98364);
insert into car (maker, model, price) values ('Cadillac', 'XLR', 62302);
insert into car (maker, model, price) values ('Chevrolet', 'Silverado', 58260);
insert into car (maker, model, price) values ('GMC', '1500 Club Coupe', 85297);
insert into car (maker, model, price) values ('Hyundai', 'Equus', 46826);
insert into car (maker, model, price) values ('Dodge', 'Grand Caravan', 97222);
insert into car (maker, model, price) values ('Maybach', '57', 68179);
insert into car (maker, model, price) values ('Isuzu', 'Hombre Space', 97850);
insert into car (maker, model, price) values ('Subaru', 'Legacy', 72413);
insert into car (maker, model, price) values ('Ford', 'E-Series', 54601);
insert into car (maker, model, price) values ('Mitsubishi', 'Mighty Max', 86482);
insert into car (maker, model, price) values ('BMW', 'M6', 90996);
insert into car (maker, model, price) values ('Porsche', 'Cayenne', 31232);
insert into car (maker, model, price) values ('Kia', 'Sephia', 88539);
insert into car (maker, model, price) values ('Lexus', 'LS', 41820);
insert into car (maker, model, price) values ('Acura', 'RDX', 56222);
insert into car (maker, model, price) values ('Lexus', 'LX', 58195);
insert into car (maker, model, price) values ('Saturn', 'Outlook', 33498);
insert into car (maker, model, price) values ('Jaguar', 'XJ', 18691);
insert into car (maker, model, price) values ('Nissan', '240SX', 80418);
insert into car (maker, model, price) values ('GMC', 'Sierra 3500', 63494);
insert into car (maker, model, price) values ('Plymouth', 'Fury', 37612);
insert into car (maker, model, price) values ('Toyota', 'Highlander', 56102);
insert into car (maker, model, price) values ('Porsche', 'Boxster', 91895);
insert into car (maker, model, price) values ('Cadillac', 'Escalade', 19658);
insert into car (maker, model, price) values ('Mazda', 'MX-5', 81080);
insert into car (maker, model, price) values ('Chevrolet', 'Express 1500', 26906);
insert into car (maker, model, price) values ('GMC', 'Envoy', 53370);
insert into car (maker, model, price) values ('Chevrolet', 'S10', 81948);
insert into car (maker, model, price) values ('Subaru', 'Impreza', 66203);
insert into car (maker, model, price) values ('Subaru', 'Legacy', 23068);
insert into car (maker, model, price) values ('Jeep', 'Liberty', 34615);
insert into car (maker, model, price) values ('Volkswagen', 'Golf', 50484);
insert into car (maker, model, price) values ('Chevrolet', 'Astro', 81782);
insert into car (maker, model, price) values ('Smart', 'Fortwo', 88559);
insert into car (maker, model, price) values ('Toyota', 'Celica', 44002);
insert into car (maker, model, price) values ('Porsche', '944', 63041);
insert into car (maker, model, price) values ('Nissan', 'Quest', 14596);
insert into car (maker, model, price) values ('Audi', 'A6', 47731);
insert into car (maker, model, price) values ('Volvo', 'S60', 47786);
insert into car (maker, model, price) values ('Pontiac', 'Grand Am', 55648);
insert into car (maker, model, price) values ('Chrysler', 'Concorde', 57529);
insert into car (maker, model, price) values ('Chevrolet', 'Malibu Maxx', 53993);
insert into car (maker, model, price) values ('Isuzu', 'Rodeo', 83768);
insert into car (maker, model, price) values ('Toyota', '4Runner', 94645);
insert into car (maker, model, price) values ('Chevrolet', 'G-Series 2500', 21921);
insert into car (maker, model, price) values ('Dodge', 'Dakota Club', 30616);
insert into car (maker, model, price) values ('Nissan', 'Altima', 50625);
insert into car (maker, model, price) values ('GMC', '3500', 45217);
insert into car (maker, model, price) values ('Ford', 'Tempo', 94543);
insert into car (maker, model, price) values ('Chevrolet', 'Monte Carlo', 12809);
insert into car (maker, model, price) values ('Mitsubishi', 'Diamante', 81384);
insert into car (maker, model, price) values ('GMC', 'Savana 1500', 58278);
insert into car (maker, model, price) values ('Chrysler', 'Sebring', 61572);
insert into car (maker, model, price) values ('Acura', 'RSX', 66211);
insert into car (maker, model, price) values ('Infiniti', 'M', 88788);
insert into car (maker, model, price) values ('Mercedes-Benz', 'M-Class', 64529);
insert into car (maker, model, price) values ('GMC', '1500 Club Coupe', 25838);
insert into car (maker, model, price) values ('Lexus', 'LS', 49498);
insert into car (maker, model, price) values ('BMW', '525', 19467);
insert into car (maker, model, price) values ('Mazda', 'B-Series', 12305);
insert into car (maker, model, price) values ('Mazda', 'Familia', 81983);
insert into car (maker, model, price) values ('Hyundai', 'Tiburon', 34116);
insert into car (maker, model, price) values ('Toyota', 'Avalon', 68398);
insert into car (maker, model, price) values ('Chevrolet', 'Astro', 73797);
insert into car (maker, model, price) values ('Volkswagen', 'Golf III', 16833);
insert into car (maker, model, price) values ('Lamborghini', 'Countach', 48615);
insert into car (maker, model, price) values ('Fiat', '500', 32895);
insert into car (maker, model, price) values ('Infiniti', 'G37', 15443);
insert into car (maker, model, price) values ('BMW', 'Z8', 20993);
insert into car (maker, model, price) values ('Acura', 'NSX', 48712);
insert into car (maker, model, price) values ('Subaru', 'Legacy', 61568);
insert into car (maker, model, price) values ('Volkswagen', 'Eurovan', 42299);
insert into car (maker, model, price) values ('Toyota', 'Avalon', 59685);
insert into car (maker, model, price) values ('GMC', 'Yukon XL', 52000);
insert into car (maker, model, price) values ('Chevrolet', 'Impala', 42969);
insert into car (maker, model, price) values ('Nissan', 'Frontier', 97502);
insert into car (maker, model, price) values ('Infiniti', 'I', 67928);
insert into car (maker, model, price) values ('Jeep', 'Grand Cherokee', 23534);
insert into car (maker, model, price) values ('Eagle', 'Vision', 98726);
insert into car (maker, model, price) values ('Cadillac', 'Escalade', 36759);
insert into car (maker, model, price) values ('Eagle', 'Vision', 36460);
insert into car (maker, model, price) values ('Saturn', 'VUE', 18491);
insert into car (maker, model, price) values ('Mitsubishi', 'GTO', 21291);
insert into car (maker, model, price) values ('Dodge', 'Neon', 76323);
insert into car (maker, model, price) values ('BMW', '7 Series', 81465);
insert into car (maker, model, price) values ('Mercedes-Benz', 'CLK-Class', 97222);
insert into car (maker, model, price) values ('Suzuki', 'Grand Vitara', 34834);
insert into car (maker, model, price) values ('Chevrolet', 'G-Series G30', 38295);
insert into car (maker, model, price) values ('Volkswagen', 'Jetta', 62867);
insert into car (maker, model, price) values ('Mercury', 'Tracer', 35852);
insert into car (maker, model, price) values ('Ford', 'Explorer', 51658);
insert into car (maker, model, price) values ('Mitsubishi', 'Challenger', 47609);
insert into car (maker, model, price) values ('Mercury', 'Mountaineer', 31965);
insert into car (maker, model, price) values ('Pontiac', 'Sunbird', 24520);
insert into car (maker, model, price) values ('GMC', 'Sonoma Club Coupe', 36215);
insert into car (maker, model, price) values ('GMC', 'Savana 3500', 89902);
insert into car (maker, model, price) values ('Mercedes-Benz', 'M-Class', 43552);
insert into car (maker, model, price) values ('Acura', 'RSX', 48880);
insert into car (maker, model, price) values ('Mercury', 'Grand Marquis', 64062);
insert into car (maker, model, price) values ('Dodge', 'Ram 1500', 47331);
insert into car (maker, model, price) values ('Ford', 'C-MAX Hybrid', 25258);
insert into car (maker, model, price) values ('Ford', 'Contour', 83600);
insert into car (maker, model, price) values ('Volkswagen', 'Passat', 92206);
insert into car (maker, model, price) values ('Acura', 'MDX', 57741);
insert into car (maker, model, price) values ('Nissan', 'Quest', 92901);
insert into car (maker, model, price) values ('Mercury', 'Villager', 42954);
insert into car (maker, model, price) values ('Ford', 'E-Series', 52236);
insert into car (maker, model, price) values ('Mercedes-Benz', 'G-Class', 84443);
insert into car (maker, model, price) values ('Nissan', 'GT-R', 64231);
insert into car (maker, model, price) values ('Suzuki', 'Swift', 10021);
insert into car (maker, model, price) values ('Aston Martin', 'Vantage', 42477);
insert into car (maker, model, price) values ('Pontiac', 'Bonneville', 80261);
insert into car (maker, model, price) values ('Jeep', 'Compass', 55305);
insert into car (maker, model, price) values ('Lamborghini', 'Reventón', 96312);
insert into car (maker, model, price) values ('Chevrolet', 'Colorado', 14579);
insert into car (maker, model, price) values ('Ford', 'Escort', 45507);
insert into car (maker, model, price) values ('GMC', 'Sierra', 21782);
insert into car (maker, model, price) values ('Pontiac', 'GTO', 85521);
insert into car (maker, model, price) values ('Mazda', 'Mazda5', 51140);
insert into car (maker, model, price) values ('Mitsubishi', 'Montero', 58929);
insert into car (maker, model, price) values ('Chevrolet', 'Caprice Classic', 41102);
insert into car (maker, model, price) values ('BMW', 'M5', 89433);
insert into car (maker, model, price) values ('Chrysler', '300', 10963);
insert into car (maker, model, price) values ('Volvo', 'XC60', 97498);
insert into car (maker, model, price) values ('Saab', '9-3', 82892);
insert into car (maker, model, price) values ('Dodge', 'Viper', 51046);
insert into car (maker, model, price) values ('Audi', 'A8', 47744);
insert into car (maker, model, price) values ('Cadillac', 'SRX', 17797);
insert into car (maker, model, price) values ('Chrysler', 'LHS', 90568);
insert into car (maker, model, price) values ('BMW', '530', 28410);
insert into car (maker, model, price) values ('Mitsubishi', 'Truck', 45921);
insert into car (maker, model, price) values ('Ford', 'F250', 57571);
insert into car (maker, model, price) values ('Volkswagen', 'New Beetle', 40636);
insert into car (maker, model, price) values ('Lincoln', 'Mark LT', 98085);
insert into car (maker, model, price) values ('Pontiac', 'Grand Am', 63272);
insert into car (maker, model, price) values ('Dodge', 'Ram 1500 Club', 86343);
insert into car (maker, model, price) values ('Dodge', 'Ram 3500', 93818);
insert into car (maker, model, price) values ('BMW', 'X3', 31830);
insert into car (maker, model, price) values ('Toyota', 'Sienna', 58877);
insert into car (maker, model, price) values ('Chrysler', 'Town & Country', 12521);
insert into car (maker, model, price) values ('Audi', 'S8', 10585);
insert into car (maker, model, price) values ('Chevrolet', 'SSR', 47595);
insert into car (maker, model, price) values ('Mercury', 'Grand Marquis', 36220);
insert into car (maker, model, price) values ('Oldsmobile', 'Silhouette', 12734);
insert into car (maker, model, price) values ('GMC', 'Sierra 3500', 30329);
insert into car (maker, model, price) values ('Nissan', 'Xterra', 15095);
insert into car (maker, model, price) values ('Honda', 'S2000', 73836);
insert into car (maker, model, price) values ('Ford', 'Expedition', 28542);
insert into car (maker, model, price) values ('Mercury', 'Mystique', 56830);
insert into car (maker, model, price) values ('Mitsubishi', 'Galant', 94928);
insert into car (maker, model, price) values ('MINI', 'Clubman', 29107);
insert into car (maker, model, price) values ('Ford', 'Econoline E250', 35639);
insert into car (maker, model, price) values ('Mercury', 'Cougar', 38323);
insert into car (maker, model, price) values ('Mitsubishi', 'Tundra', 72625);
insert into car (maker, model, price) values ('Acura', 'RL', 88637);
insert into car (maker, model, price) values ('Lincoln', 'Aviator', 20352);
insert into car (maker, model, price) values ('Ford', 'Model T', 59985);
insert into car (maker, model, price) values ('Ford', 'Escape', 39309);
insert into car (maker, model, price) values ('Nissan', 'Pathfinder', 11647);
insert into car (maker, model, price) values ('Subaru', 'Impreza', 56806);
insert into car (maker, model, price) values ('Lincoln', 'Mark VIII', 81774);
insert into car (maker, model, price) values ('Ford', 'Tempo', 98095);
insert into car (maker, model, price) values ('Chevrolet', 'Cavalier', 47386);
insert into car (maker, model, price) values ('Dodge', 'Stratus', 44621);
insert into car (maker, model, price) values ('Volkswagen', 'Fox', 10680);
insert into car (maker, model, price) values ('Infiniti', 'FX', 53722);
insert into car (maker, model, price) values ('Mercedes-Benz', 'SL-Class', 77370);
insert into car (maker, model, price) values ('Corbin', 'Sparrow', 97544);
insert into car (maker, model, price) values ('Dodge', 'Ram 1500 Club', 45296);
insert into car (maker, model, price) values ('MINI', 'Clubman', 90212);
insert into car (maker, model, price) values ('Aptera', 'Typ-1', 17037);
insert into car (maker, model, price) values ('Audi', 'A6', 97854);
insert into car (maker, model, price) values ('Mazda', 'Tribute', 62769);
insert into car (maker, model, price) values ('Buick', 'Skyhawk', 67077);
insert into car (maker, model, price) values ('Pontiac', 'Firebird', 88647);
insert into car (maker, model, price) values ('Hyundai', 'Santa Fe', 56511);
insert into car (maker, model, price) values ('Saturn', 'L-Series', 51609);
insert into car (maker, model, price) values ('Chevrolet', 'Suburban', 28483);
insert into car (maker, model, price) values ('Chevrolet', 'Venture', 87352);
insert into car (maker, model, price) values ('Suzuki', 'Swift', 92605);
insert into car (maker, model, price) values ('Kia', 'Mentor', 31927);
insert into car (maker, model, price) values ('Mitsubishi', 'L300', 23681);
insert into car (maker, model, price) values ('Mazda', 'B-Series Plus', 25993);
insert into car (maker, model, price) values ('Cadillac', 'Escalade EXT', 62215);
insert into car (maker, model, price) values ('Mitsubishi', 'Galant', 36873);
insert into car (maker, model, price) values ('Subaru', 'Alcyone SVX', 37794);
insert into car (maker, model, price) values ('Audi', 'S8', 24443);
insert into car (maker, model, price) values ('Chevrolet', 'Astro', 85584);
insert into car (maker, model, price) values ('Mercedes-Benz', 'G-Class', 51093);
insert into car (maker, model, price) values ('Buick', 'Riviera', 32950);
insert into car (maker, model, price) values ('BMW', 'X3', 54078);
insert into car (maker, model, price) values ('Dodge', 'Caliber', 28586);
insert into car (maker, model, price) values ('Acura', 'Legend', 25398);
insert into car (maker, model, price) values ('Infiniti', 'Q', 76569);
insert into car (maker, model, price) values ('GMC', 'Sierra 2500', 12711);
insert into car (maker, model, price) values ('Volkswagen', 'GTI', 43855);
insert into car (maker, model, price) values ('Porsche', 'Panamera', 80101);
insert into car (maker, model, price) values ('Dodge', 'Ram 2500 Club', 67592);
insert into car (maker, model, price) values ('Volkswagen', 'Cabriolet', 75506);
insert into car (maker, model, price) values ('GMC', 'Sonoma', 58439);
insert into car (maker, model, price) values ('Ford', 'Probe', 99880);
insert into car (maker, model, price) values ('Oldsmobile', 'Silhouette', 94084);
insert into car (maker, model, price) values ('Lotus', 'Elise', 58188);
insert into car (maker, model, price) values ('Chrysler', 'Crossfire', 80288);
insert into car (maker, model, price) values ('Subaru', 'Outback', 11147);
insert into car (maker, model, price) values ('Suzuki', 'XL7', 38642);
insert into car (maker, model, price) values ('Mercedes-Benz', 'SL-Class', 12722);
insert into car (maker, model, price) values ('Dodge', 'Monaco', 24653);
insert into car (maker, model, price) values ('Daewoo', 'Leganza', 81328);
insert into car (maker, model, price) values ('Ford', 'Courier', 74005);
insert into car (maker, model, price) values ('Subaru', 'Legacy', 78671);
insert into car (maker, model, price) values ('Pontiac', 'Firebird', 44193);
insert into car (maker, model, price) values ('Subaru', 'SVX', 92930);
insert into car (maker, model, price) values ('Dodge', 'Ram 2500', 67164);
insert into car (maker, model, price) values ('Mercedes-Benz', 'CLS-Class', 58490);
insert into car (maker, model, price) values ('Mazda', 'Mazda2', 44934);
insert into car (maker, model, price) values ('Pontiac', '1000', 89627);
insert into car (maker, model, price) values ('MINI', 'Cooper', 29388);
insert into car (maker, model, price) values ('Land Rover', 'Range Rover', 48941);
insert into car (maker, model, price) values ('Ford', 'F350', 43754);
insert into car (maker, model, price) values ('Saturn', 'S-Series', 44492);
insert into car (maker, model, price) values ('GMC', 'Savana 2500', 90476);
insert into car (maker, model, price) values ('Lexus', 'GS', 44974);
insert into car (maker, model, price) values ('Jeep', 'Patriot', 36870);
insert into car (maker, model, price) values ('Audi', '5000S', 66825);
insert into car (maker, model, price) values ('Subaru', 'Forester', 21587);
insert into car (maker, model, price) values ('Chevrolet', 'Corsica', 70489);
insert into car (maker, model, price) values ('Subaru', 'Legacy', 56170);
insert into car (maker, model, price) values ('GMC', 'Yukon XL 1500', 68604);
insert into car (maker, model, price) values ('GMC', 'Sonoma', 12594);
insert into car (maker, model, price) values ('Volkswagen', 'New Beetle', 59571);
insert into car (maker, model, price) values ('Jeep', 'Commander', 15625);
insert into car (maker, model, price) values ('Mercedes-Benz', 'C-Class', 35079);
insert into car (maker, model, price) values ('Oldsmobile', 'Bravada', 18692);
insert into car (maker, model, price) values ('Maserati', 'Quattroporte', 61731);
insert into car (maker, model, price) values ('Dodge', 'Grand Caravan', 10305);
insert into car (maker, model, price) values ('Dodge', 'Neon', 93698);
insert into car (maker, model, price) values ('Cadillac', 'Escalade EXT', 76606);
insert into car (maker, model, price) values ('Pontiac', 'Sunbird', 11128);
insert into car (maker, model, price) values ('Toyota', 'Tacoma Xtra', 58685);
insert into car (maker, model, price) values ('BMW', '1 Series', 24856);
insert into car (maker, model, price) values ('Nissan', 'Titan', 99643);
insert into car (maker, model, price) values ('Volvo', 'C70', 16262);
insert into car (maker, model, price) values ('Mazda', 'RX-8', 40351);
insert into car (maker, model, price) values ('Porsche', 'Cayenne', 77806);
insert into car (maker, model, price) values ('Chevrolet', 'Camaro', 89988);
insert into car (maker, model, price) values ('Dodge', 'Dakota Club', 25227);
insert into car (maker, model, price) values ('Saab', '9000', 28296);
insert into car (maker, model, price) values ('Nissan', 'Murano', 14191);
insert into car (maker, model, price) values ('Toyota', 'Camry', 53472);
insert into car (maker, model, price) values ('Subaru', 'Legacy', 22389);
insert into car (maker, model, price) values ('GMC', '2500', 72800);
insert into car (maker, model, price) values ('Volkswagen', 'Fox', 81288);
insert into car (maker, model, price) values ('Suzuki', 'Verona', 92765);
insert into car (maker, model, price) values ('BMW', '3 Series', 51731);
insert into car (maker, model, price) values ('Lincoln', 'MKT', 91870);
insert into car (maker, model, price) values ('Ford', 'Fairlane', 54995);
insert into car (maker, model, price) values ('Toyota', 'Tacoma', 31868);
insert into car (maker, model, price) values ('Chevrolet', 'Express 1500', 94511);
insert into car (maker, model, price) values ('Dodge', 'Ram 1500 Club', 55373);
insert into car (maker, model, price) values ('Mazda', 'B-Series', 74400);
insert into car (maker, model, price) values ('Volkswagen', 'Golf III', 56011);
insert into car (maker, model, price) values ('GMC', 'Suburban 1500', 17303);
insert into car (maker, model, price) values ('Mazda', '929', 88517);
insert into car (maker, model, price) values ('Toyota', 'Camry Hybrid', 58702);
insert into car (maker, model, price) values ('Mercedes-Benz', 'E-Class', 37374);
insert into car (maker, model, price) values ('Mazda', 'MX-6', 94738);
insert into car (maker, model, price) values ('Nissan', 'Rogue', 33177);
insert into car (maker, model, price) values ('Cadillac', 'CTS-V', 70434);
insert into car (maker, model, price) values ('Toyota', 'MR2', 23819);
insert into car (maker, model, price) values ('Cadillac', 'SRX', 26482);
insert into car (maker, model, price) values ('Mercedes-Benz', 'CL-Class', 14183);
insert into car (maker, model, price) values ('BMW', 'Z4', 86313);
insert into car (maker, model, price) values ('Mercury', 'Cougar', 81731);
insert into car (maker, model, price) values ('Subaru', 'Leone', 11849);
insert into car (maker, model, price) values ('Cadillac', 'XLR', 88697);
insert into car (maker, model, price) values ('Honda', 'del Sol', 36939);
insert into car (maker, model, price) values ('Chevrolet', 'Cobalt SS', 87702);
insert into car (maker, model, price) values ('Land Rover', 'Range Rover', 90999);
insert into car (maker, model, price) values ('GMC', '1500 Club Coupe', 91345);
insert into car (maker, model, price) values ('Toyota', 'Solara', 30880);
insert into car (maker, model, price) values ('Chevrolet', 'Avalanche', 33818);
insert into car (maker, model, price) values ('Volkswagen', 'Touareg', 48658);
insert into car (maker, model, price) values ('Maserati', 'Quattroporte', 66076);
insert into car (maker, model, price) values ('Chevrolet', 'Corvette', 31713);
insert into car (maker, model, price) values ('Volvo', 'S60', 80434);
insert into car (maker, model, price) values ('Kia', 'Mentor', 27591);
insert into car (maker, model, price) values ('Mazda', '929', 60869);
insert into car (maker, model, price) values ('Dodge', 'Grand Caravan', 57469);
insert into car (maker, model, price) values ('BMW', '330', 21760);
insert into car (maker, model, price) values ('Mitsubishi', 'Montero', 64592);
insert into car (maker, model, price) values ('MINI', 'Countryman', 51829);
insert into car (maker, model, price) values ('Lincoln', 'Continental', 16688);
insert into car (maker, model, price) values ('Mazda', 'B-Series', 77451);
insert into car (maker, model, price) values ('Pontiac', 'Daewoo Kalos', 25267);
insert into car (maker, model, price) values ('Mitsubishi', 'Sigma', 95308);
insert into car (maker, model, price) values ('Jaguar', 'XJ Series', 92753);
insert into car (maker, model, price) values ('Chevrolet', 'Malibu', 45424);
insert into car (maker, model, price) values ('GMC', 'Acadia', 34159);
insert into car (maker, model, price) values ('Mazda', 'RX-7', 44700);
insert into car (maker, model, price) values ('Cadillac', 'XLR', 59158);
insert into car (maker, model, price) values ('Oldsmobile', 'Cutlass', 16644);
insert into car (maker, model, price) values ('Hyundai', 'Scoupe', 33409);
insert into car (maker, model, price) values ('Porsche', '911', 30738);
insert into car (maker, model, price) values ('Pontiac', 'Chevette', 11667);
insert into car (maker, model, price) values ('Chrysler', '300M', 61712);
insert into car (maker, model, price) values ('Volkswagen', 'GTI', 72562);
insert into car (maker, model, price) values ('Chevrolet', 'Camaro', 16123);
insert into car (maker, model, price) values ('Chevrolet', 'Suburban 2500', 42207);
insert into car (maker, model, price) values ('Chevrolet', 'Sportvan G30', 61226);
insert into car (maker, model, price) values ('Mitsubishi', 'Lancer', 99082);
insert into car (maker, model, price) values ('Chevrolet', 'Express 3500', 68726);
insert into car (maker, model, price) values ('Pontiac', 'Firebird', 65612);
insert into car (maker, model, price) values ('Chevrolet', 'Aveo', 43969);
insert into car (maker, model, price) values ('Oldsmobile', 'Bravada', 42972);
insert into car (maker, model, price) values ('Volkswagen', 'Passat', 73065);
insert into car (maker, model, price) values ('Nissan', 'Frontier', 45614);
insert into car (maker, model, price) values ('BMW', 'Z3', 21070);
insert into car (maker, model, price) values ('Pontiac', 'GTO', 49097);
insert into car (maker, model, price) values ('Oldsmobile', 'Toronado', 62999);
insert into car (maker, model, price) values ('Volkswagen', 'Cabriolet', 38049);
insert into car (maker, model, price) values ('Nissan', 'JUKE', 66606);
insert into car (maker, model, price) values ('Toyota', 'MR2', 94840);
insert into car (maker, model, price) values ('Mazda', 'RX-7', 38155);
insert into car (maker, model, price) values ('Pontiac', 'Grand Prix', 89994);
insert into car (maker, model, price) values ('Volkswagen', 'Scirocco', 83558);
insert into car (maker, model, price) values ('Chevrolet', 'Express 3500', 33301);
insert into car (maker, model, price) values ('Audi', 'TT', 79098);
insert into car (maker, model, price) values ('Mercedes-Benz', 'C-Class', 69724);
insert into car (maker, model, price) values ('Mercedes-Benz', 'E-Class', 55448);
insert into car (maker, model, price) values ('Infiniti', 'G37', 29173);
insert into car (maker, model, price) values ('Nissan', 'Maxima', 33743);
insert into car (maker, model, price) values ('Volkswagen', 'Passat', 62516);
insert into car (maker, model, price) values ('Infiniti', 'G', 17238);
insert into car (maker, model, price) values ('Plymouth', 'Grand Voyager', 99074);
insert into car (maker, model, price) values ('Saturn', 'S-Series', 69983);
insert into car (maker, model, price) values ('Pontiac', 'Safari', 14200);
insert into car (maker, model, price) values ('Acura', 'TL', 31515);
insert into car (maker, model, price) values ('Suzuki', 'Esteem', 84567);
insert into car (maker, model, price) values ('Honda', 'Element', 44982);
insert into car (maker, model, price) values ('Pontiac', 'Montana', 61744);
insert into car (maker, model, price) values ('Mercedes-Benz', 'SL-Class', 79532);
insert into car (maker, model, price) values ('Mitsubishi', 'Eclipse', 15014);
insert into car (maker, model, price) values ('Ford', 'Explorer', 12263);
insert into car (maker, model, price) values ('Dodge', 'Viper', 52128);
insert into car (maker, model, price) values ('Toyota', 'Supra', 41857);
insert into car (maker, model, price) values ('Saab', '9-5', 22343);
insert into car (maker, model, price) values ('Kia', 'Optima', 59824);
insert into car (maker, model, price) values ('Chevrolet', 'Suburban', 38005);
insert into car (maker, model, price) values ('Mazda', 'B-Series', 69071);
insert into car (maker, model, price) values ('Ferrari', '612 Scaglietti', 51205);
insert into car (maker, model, price) values ('Jeep', 'Wrangler', 17270);
insert into car (maker, model, price) values ('Buick', 'Park Avenue', 23488);
insert into car (maker, model, price) values ('Pontiac', 'G5', 36281);
insert into car (maker, model, price) values ('Mazda', 'B-Series', 15063);
insert into car (maker, model, price) values ('Chrysler', 'Town & Country', 75479);
insert into car (maker, model, price) values ('Mercedes-Benz', 'CLS-Class', 30748);
insert into car (maker, model, price) values ('Chevrolet', 'Corvette', 13363);
insert into car (maker, model, price) values ('Pontiac', 'GTO', 44257);
insert into car (maker, model, price) values ('Pontiac', '1000', 61139);
insert into car (maker, model, price) values ('Chevrolet', 'G-Series G10', 12684);
insert into car (maker, model, price) values ('Toyota', 'Corolla', 80612);
insert into car (maker, model, price) values ('Chevrolet', 'Impala', 46078);
insert into car (maker, model, price) values ('Mazda', 'Millenia', 98630);
insert into car (maker, model, price) values ('Ford', 'Crown Victoria', 43921);
insert into car (maker, model, price) values ('Chrysler', 'Sebring', 10288);
insert into car (maker, model, price) values ('Chevrolet', 'Impala', 25303);
insert into car (maker, model, price) values ('Lotus', 'Elise', 17926);
insert into car (maker, model, price) values ('Saab', '9-5', 56336);
insert into car (maker, model, price) values ('Subaru', 'Legacy', 13183);
insert into car (maker, model, price) values ('Ford', 'E-Series', 96991);
insert into car (maker, model, price) values ('Aston Martin', 'DB9', 21075);
insert into car (maker, model, price) values ('Ford', 'Mustang', 15930);
insert into car (maker, model, price) values ('Dodge', 'Durango', 38440);
insert into car (maker, model, price) values ('Chevrolet', 'Suburban 2500', 83599);
insert into car (maker, model, price) values ('Oldsmobile', '98', 58624);
insert into car (maker, model, price) values ('Volvo', 'XC70', 79469);
insert into car (maker, model, price) values ('Dodge', 'Dakota Club', 75284);
insert into car (maker, model, price) values ('Ford', 'F450', 20825);
insert into car (maker, model, price) values ('Mercedes-Benz', 'CL-Class', 20795);
insert into car (maker, model, price) values ('Suzuki', 'Aerio', 34580);
insert into car (maker, model, price) values ('Mazda', 'Tribute', 60392);
insert into car (maker, model, price) values ('Mitsubishi', 'Diamante', 92469);
insert into car (maker, model, price) values ('Toyota', 'RAV4', 21407);
insert into car (maker, model, price) values ('Ford', 'E250', 12744);
insert into car (maker, model, price) values ('Ford', 'Edge', 29268);
insert into car (maker, model, price) values ('Chevrolet', 'Silverado 3500', 89132);
insert into car (maker, model, price) values ('Cadillac', 'Escalade', 71823);
insert into car (maker, model, price) values ('Mitsubishi', 'Montero', 54744);
insert into car (maker, model, price) values ('MINI', 'Cooper Countryman', 93821);
insert into car (maker, model, price) values ('Nissan', 'Maxima', 52229);
insert into car (maker, model, price) values ('Mercedes-Benz', 'M-Class', 98169);
insert into car (maker, model, price) values ('Ford', 'Escort', 83208);
insert into car (maker, model, price) values ('Ford', 'F350', 82782);
insert into car (maker, model, price) values ('Toyota', '4Runner', 10489);
insert into car (maker, model, price) values ('Suzuki', 'SX4', 11203);
insert into car (maker, model, price) values ('Nissan', 'Maxima', 71682);
insert into car (maker, model, price) values ('Pontiac', 'Daewoo Kalos', 49944);
insert into car (maker, model, price) values ('Ford', 'F150', 76595);
insert into car (maker, model, price) values ('GMC', 'Sonoma', 24541);
insert into car (maker, model, price) values ('Pontiac', 'Bonneville', 86890);
insert into car (maker, model, price) values ('BMW', 'M', 75244);
insert into car (maker, model, price) values ('Mitsubishi', 'Diamante', 63450);
insert into car (maker, model, price) values ('Mitsubishi', 'Truck', 10741);
insert into car (maker, model, price) values ('Ford', 'Windstar', 72418);
insert into car (maker, model, price) values ('Mitsubishi', 'Montero', 96694);
insert into car (maker, model, price) values ('Chevrolet', 'Cavalier', 79134);
insert into car (maker, model, price) values ('Mercedes-Benz', 'CLK-Class', 72457);
insert into car (maker, model, price) values ('Pontiac', 'Bonneville', 76497);
insert into car (maker, model, price) values ('Volkswagen', 'GTI', 75550);
insert into car (maker, model, price) values ('Hyundai', 'Azera', 64697);
insert into car (maker, model, price) values ('Ford', 'GT500', 52310);
insert into car (maker, model, price) values ('Mitsubishi', 'Pajero', 25038);
insert into car (maker, model, price) values ('Chrysler', 'Concorde', 37651);
insert into car (maker, model, price) values ('GMC', 'Envoy XL', 80189);
insert into car (maker, model, price) values ('Audi', 'TT', 20611);
insert into car (maker, model, price) values ('Jeep', 'Wrangler', 14572);
insert into car (maker, model, price) values ('Infiniti', 'FX', 98350);
insert into car (maker, model, price) values ('Nissan', 'Sentra', 62622);
insert into car (maker, model, price) values ('Maserati', 'Spyder', 29340);
insert into car (maker, model, price) values ('Hummer', 'H2', 81914);
insert into car (maker, model, price) values ('Mazda', 'Protege', 14775);
insert into car (maker, model, price) values ('Buick', 'LaCrosse', 43818);
insert into car (maker, model, price) values ('Pontiac', 'Vibe', 40594);
insert into car (maker, model, price) values ('Nissan', 'Xterra', 98698);
insert into car (maker, model, price) values ('Land Rover', 'LR4', 13089);
insert into car (maker, model, price) values ('Pontiac', 'Grand Prix', 15968);
insert into car (maker, model, price) values ('Toyota', 'RAV4', 38536);
insert into car (maker, model, price) values ('Lotus', 'Elan', 29130);
insert into car (maker, model, price) values ('Isuzu', 'Hombre Space', 34258);
insert into car (maker, model, price) values ('Mitsubishi', 'Lancer Evolution', 58693);
insert into car (maker, model, price) values ('Toyota', 'T100', 27669);
insert into car (maker, model, price) values ('Audi', 'A8', 72520);
insert into car (maker, model, price) values ('Ford', 'Mustang', 94984);
insert into car (maker, model, price) values ('Infiniti', 'M', 85641);
insert into car (maker, model, price) values ('Audi', 'Q5', 44104);
insert into car (maker, model, price) values ('Mitsubishi', 'GTO', 61443);
insert into car (maker, model, price) values ('Toyota', 'Sequoia', 10119);
insert into car (maker, model, price) values ('Ford', 'E-Series', 32786);
insert into car (maker, model, price) values ('Mercedes-Benz', 'SL-Class', 52690);
insert into car (maker, model, price) values ('Volvo', 'XC90', 28697);
insert into car (maker, model, price) values ('Pontiac', 'Bonneville', 54053);
insert into car (maker, model, price) values ('Chevrolet', 'Silverado 2500', 28636);
insert into car (maker, model, price) values ('Volvo', 'S60', 49690);
insert into car (maker, model, price) values ('Isuzu', 'i-370', 90555);
insert into car (maker, model, price) values ('Chevrolet', 'Silverado 3500', 81874);
insert into car (maker, model, price) values ('Mitsubishi', 'Endeavor', 57872);
insert into car (maker, model, price) values ('Buick', 'Hearse', 29159);
insert into car (maker, model, price) values ('Jaguar', 'XF', 79325);
insert into car (maker, model, price) values ('Ford', 'Econoline E350', 16932);
insert into car (maker, model, price) values ('Land Rover', 'Discovery', 90340);
insert into car (maker, model, price) values ('Mazda', 'Mazda5', 19314);
insert into car (maker, model, price) values ('Mercury', 'Sable', 26857);
insert into car (maker, model, price) values ('Pontiac', 'Sunbird', 27978);
insert into car (maker, model, price) values ('Ford', 'Ranger', 22429);
insert into car (maker, model, price) values ('GMC', 'Yukon XL 1500', 53000);
insert into car (maker, model, price) values ('Mitsubishi', 'Truck', 80541);
insert into car (maker, model, price) values ('Mitsubishi', 'Pajero', 82446);
insert into car (maker, model, price) values ('Pontiac', 'GTO', 86156);
insert into car (maker, model, price) values ('Kia', 'Optima', 30182);
insert into car (maker, model, price) values ('Mazda', 'RX-7', 38253);
insert into car (maker, model, price) values ('Volkswagen', 'Golf', 67665);
insert into car (maker, model, price) values ('GMC', 'Sierra', 65252);
insert into car (maker, model, price) values ('Toyota', 'Yaris', 52266);
